# Generated by Django 4.2.1 on 2023-09-16 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LocalArmonia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('foto', models.ImageField(blank='', default='', upload_to='localFoto/')),
                ('localidad', models.CharField(max_length=60, null=True)),
                ('domicilio', models.CharField(max_length=60, null=True)),
                ('cuil', models.CharField(max_length=40, null=True, unique=True)),
                ('fechaCreacion', models.DateField(blank='', default=None, null=True)),
                ('numeroTelefonico', models.CharField(max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Residente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreResidente', models.CharField(max_length=40)),
                ('apellidoResidente', models.CharField(max_length=40)),
                ('dniResidente', models.CharField(max_length=8, unique=True)),
                ('fechaNacimiento', models.DateField(default=None)),
                ('edad', models.IntegerField(default='Edad del residente')),
                ('genero', models.CharField(choices=[('0', 'Masculino'), ('1', 'Femenino'), ('2', 'No responder')], max_length=1)),
                ('fotoResidente', models.ImageField(blank='', default='', upload_to='residentesFoto/')),
                ('medicoDeCabecera', models.CharField(max_length=40)),
                ('grupoSanguineo', models.CharField(choices=[('0', 'A+'), ('1', 'O+'), ('2', 'B+'), ('3', 'AB+'), ('4', 'A-'), ('5', 'O-'), ('6', 'B-'), ('7', 'AB-')], max_length=1)),
                ('numeroDeHabitacion', models.CharField(max_length=40)),
                ('observacionesResidente', models.TextField(blank=True, default='SOME STRING', null=True)),
                ('localidadFamiliar', models.CharField(default='Localidad', max_length=60)),
                ('domicilioFamiliar', models.CharField(default='Domicilio', max_length=60)),
                ('nombreFamiliar', models.CharField(max_length=40)),
                ('apellidoFamiliar', models.CharField(max_length=40)),
                ('numeroTelefonico', models.CharField(max_length=40)),
                ('dniFamiliar', models.CharField(default='Dni familiar', max_length=8, unique=True)),
                ('numeroAfiliado', models.IntegerField(unique=True)),
                ('obraSocial', models.CharField(max_length=40)),
                ('vinculoConElResidente', models.CharField(choices=[('0', 'Padre'), ('1', 'Madre'), ('2', 'Hijo'), ('3', 'Hija'), ('4', 'Abuelo'), ('5', 'Abuela'), ('6', 'Tío'), ('7', 'Tía'), ('8', 'Pariente lejano'), ('9', 'Prefiero no responder')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=50)),
                ('ifLogged', models.BooleanField(default=False)),
                ('token', models.CharField(default='', max_length=200, null=True)),
                ('cargo', models.CharField(choices=[('0', 'invitado'), ('1', 'Empleado diario'), ('2', 'Enfermero/a'), ('3', 'Medico/a'), ('4', 'Admin')], max_length=1)),
                ('fotoUser', models.ImageField(blank=True, default='', upload_to='usersFoto/')),
                ('descriptionUser', models.TextField(blank=True, default='', max_length=400, null=True)),
                ('numCelular', models.CharField(blank=True, default='', max_length=40, null=True)),
                ('direccion', models.CharField(blank=True, max_length=100, null=True)),
                ('birthday', models.DateField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StockMedicamentosResidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genericMedicamento', models.CharField(choices=[('Y', 'Si'), ('N', 'No')], max_length=1)),
                ('nombreMedicamento', models.CharField(max_length=80)),
                ('marcaMedicamento', models.CharField(max_length=60)),
                ('pesoMedicamento', models.CharField(max_length=35)),
                ('medicionMedicamento', models.CharField(choices=[('0', 'ml'), ('1', 'g'), ('2', 'píldora/as'), ('3', 'caja/as'), ('4', 'frasco/os')], max_length=1)),
                ('codMedicamento', models.CharField(max_length=50)),
                ('observacionesMedicamento', models.TextField(blank=True, default='SOME STRING', null=True)),
                ('derivacionesMedicamento', models.TextField(blank=True, default='SOME STRING', null=True)),
                ('fechaInicio', models.DateField()),
                ('cantidadTotal', models.IntegerField()),
                ('cantidadDiaria', models.IntegerField()),
                ('cantidadDisponible', models.IntegerField(blank=True, null=True)),
                ('residenteM', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicamentos', to='quickstart.residente')),
            ],
        ),
        migrations.CreateModel(
            name='StockMedicamentosLocal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genericMedicamento', models.CharField(choices=[('Y', 'Si'), ('N', 'No')], max_length=1)),
                ('nombreMedicamento', models.CharField(max_length=80)),
                ('marcaMedicamento', models.CharField(max_length=60)),
                ('pesoMedicamento', models.CharField(max_length=35)),
                ('medicionMedicamento', models.CharField(choices=[('0', 'ml'), ('1', 'g'), ('2', 'píldora/as'), ('3', 'caja/as'), ('4', 'frasco/os')], max_length=1)),
                ('codMedicamento', models.CharField(max_length=50)),
                ('observacionesMedicamento', models.TextField(blank=True, default='SOME STRING', null=True)),
                ('derivacionesMedicamento', models.TextField(blank=True, default='SOME STRING', null=True)),
                ('fechaInicio', models.DateField()),
                ('cantidadTotal', models.IntegerField()),
                ('cantidadDiaria', models.IntegerField()),
                ('cantidadDisponible', models.IntegerField(blank=True, null=True)),
                ('localA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localMedicamentos', to='quickstart.localarmonia')),
            ],
        ),
        migrations.CreateModel(
            name='ObservaciónSemanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaConsulta', models.DateField(auto_now_add=True)),
                ('tensionArterial', models.CharField(max_length=20)),
                ('glucemia', models.CharField(max_length=20)),
                ('saturacion', models.CharField(max_length=20)),
                ('pulso', models.CharField(max_length=30)),
                ('observacionesSemanales', models.TextField(blank=True, default='some string', null=True)),
                ('derivacionesSemanales', models.TextField(blank=True, default='some string2', null=True)),
                ('residenteS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signosVitales', to='quickstart.residente')),
            ],
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.CharField(max_length=255)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('leida', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.user')),
            ],
        ),
        migrations.CreateModel(
            name='CuracionesResidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaRealizada', models.DateField(auto_now_add=True)),
                ('medicacionAplicada', models.CharField(max_length=60)),
                ('profesional', models.CharField(max_length=40)),
                ('residenteC', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curaciones', to='quickstart.residente')),
            ],
        ),
    ]
