# Generated by Django 4.2.4 on 2023-09-13 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmedicamentoslocal',
            name='fechaInicio',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='stockmedicamentosresidente',
            name='fechaInicio',
            field=models.DateField(),
        ),
    ]
