# Generated by Django 4.2.4 on 2023-08-18 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmedicamentosresidente',
            name='fechaCaducidad',
            field=models.DateField(default=None),
        ),
        migrations.CreateModel(
            name='signosVitales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('residenteS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signosVitales', to='quickstart.residente')),
            ],
        ),
    ]
