# Generated by Django 4.2.4 on 2023-09-24 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residente',
            name='fotoResidente',
            field=models.ImageField(blank=True, default='', null=True, upload_to='residentesFoto/'),
        ),
    ]
