# Generated by Django 4.2.4 on 2023-09-03 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='residente',
            name='fotoResidente',
            field=models.ImageField(blank='', default='', upload_to='residentesFoto/'),
        ),
    ]
