# Generated by Django 4.2.4 on 2023-09-13 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0002_alter_stockmedicamentoslocal_fechainicio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observaciónsemanal',
            name='derivacionesSemanales',
            field=models.TextField(blank=True, default='some string2', null=True),
        ),
        migrations.AlterField(
            model_name='observaciónsemanal',
            name='observacionesSemanales',
            field=models.TextField(blank=True, default='some string', null=True),
        ),
        migrations.AlterField(
            model_name='residente',
            name='observacionesResidente',
            field=models.TextField(blank=True, default='SOME STRING', null=True),
        ),
        migrations.AlterField(
            model_name='stockmedicamentoslocal',
            name='derivacionesMedicamento',
            field=models.TextField(blank=True, default='SOME STRING', null=True),
        ),
        migrations.AlterField(
            model_name='stockmedicamentoslocal',
            name='observacionesMedicamento',
            field=models.TextField(blank=True, default='SOME STRING', null=True),
        ),
        migrations.AlterField(
            model_name='stockmedicamentosresidente',
            name='derivacionesMedicamento',
            field=models.TextField(blank=True, default='SOME STRING', null=True),
        ),
        migrations.AlterField(
            model_name='stockmedicamentosresidente',
            name='observacionesMedicamento',
            field=models.TextField(blank=True, default='SOME STRING', null=True),
        ),
    ]
