# Generated by Django 4.2.4 on 2023-08-18 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0002_stockmedicamentosresidente_fechacaducidad_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObservaciónSemanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaConsulta', models.DateField(auto_now_add=True)),
                ('tensionArterial', models.CharField(max_length=20)),
                ('glucemia', models.CharField(max_length=20)),
                ('saturacion', models.CharField(max_length=20)),
                ('pulso', models.CharField(max_length=30)),
                ('observacionesSemanales', models.TextField(default='some string')),
                ('derivacionesSemanales', models.TextField(default='some string2')),
                ('residenteS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signosVitales', to='quickstart.residente')),
            ],
        ),
        migrations.DeleteModel(
            name='signosVitales',
        ),
    ]
